//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCard.E2010GUI.Startup {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class ModuleE2010 : global::System.Configuration.ApplicationSettingsBase {
        
        private static ModuleE2010 defaultInstance = ((ModuleE2010)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ModuleE2010())));
        
        public static ModuleE2010 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double InputRateInkHz {
            get {
                return ((double)(this["InputRateInkHz"]));
            }
            set {
                this["InputRateInkHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InputRange {
            get {
                return ((int)(this["InputRange"]));
            }
            set {
                this["InputRange"] = value;
            }
        }
    }
}
